insert into Post(title, category, author_id) values('Post1', 'Joke', '1');
insert into Post(title, category, author_id) values('Post2', 'Dark', '2');
insert into Post(title, category, author_id) values('Post3', 'Personal', '3');
insert into Post(title, category, author_id) values('Post4', 'Joke', '1');
insert into Post(title, category, author_id) values('Post5', 'Profile Photo', '2');
insert into Post(title, category, author_id) values('Post6', 'Image', '3');
insert into Post(title, category, author_id) values('Post7', 'Dark', '1');
insert into Post(title, category, author_id) values('Post8', 'Joke', '2');
insert into Post(title, category, author_id) values('Post9', 'Image', '3');
insert into Post(title, category, author_id) values('Post10', 'Meme', '1');
