insert into Post(title, category, authorId) values('Post1', 'Joke', 1);
insert into Post(title, category, authorId) values('Post2', 'Dark', 2);
insert into Post(title, category, authorId) values('Post3', 'Personal', 3);
insert into Post(title, category, authorId) values('Post4', 'Joke', 1);
insert into Post(title, category, authorId) values('Post5', 'Profile Photo', 2);
insert into Post(title, category, authorId) values('Post6', 'Image', 3);
insert into Post(title, category, authorId) values('Post7', 'Dark', 1);
insert into Post(title, category, authorId) values('Post8', 'Joke', 2);
insert into Post(title, category, authorId) values('Post9', 'Image', 3);
insert into Post(title, category, authorId) values('Post10', 'Meme', 1);
